### ISSUE TITLE
Subsequent uppercase letters are not converted

### ISSUE THREAD

**Issue by sqren** [sindresorhus/camelcase#17]
Subsequent uppercase letters in a string are not converted to lowercase.

**Example:**
"XMLHttpRequest" is converted to "xMLHttpRequest" rather than "xmlHttpRequest". 

**Compared with Lodash**

``` js
const camelCase = require('camelcase');
const _ = require('lodash');

camelCase('XMLHttpRequest'); // xMLHttpRequest
_.camelCase('XMLHttpRequest'); // xmlHttpRequest
```

Is this the intended behaviour?

**Comment by sindresorhus** [comment]
Yeah, makes sense. I just never considered that use-case. PR welcome for a fix :)

**Comment by portgasd666** [comment]
If this is fixed, what would be the expected outputs for `camelCase('FBBazzy')` ?

**Comment by SamVerschueren** [comment]
`fbBazzy` probably

**Comment by portgasd666** [comment]
I've fixed it for all the test cases including a few new test cases except for those cases which contain characters from Unicode planes other than the basic plane. It fails for this test case :

`t.is(fn('FBBÈzzy'), 'fbbÈzzy');`

This test case is `t.is(fn('FBBÈzzy'), 'fBBÈzzy');` in the current version and passes because only the first character is compared. The current version produces the wrong answer when a character such as È occurs after a `-` before the final step is run.

`camelCase('Ab-Èb') == 'ab-èb'`

This is down to the fact that Regexes before ES6 are not Unicode aware I presume ?

**Comment by jdalton** [comment]
> camelCase('Ab-Èb') == 'ab-èb'

For reference Lodash deburrs Latin-1 Supplement and Latin Extended-A block characters:
```js
_.camelCase('Ab-Èb')
// => "abEb"
```
